# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: janis-vitols.com
email:
description: > # this means to ignore newlines until "baseurl:"
  Blog about Web Application testing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://janis-vitols.com" # the base hostname & protocol for your site
twitter_username:
github_username: janis-vitols
disqus_shortname: janis-vitols

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "/page/:num/"

gems:
- jemoji
- jekyll-paginate
